# Generated by Django 4.2

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('specialization', models.CharField(max_length=150)),
                ('license_no', models.CharField(max_length=100, unique=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('profile_photo', models.CharField(blank=True, max_length=500)),
                ('is_online', models.BooleanField(default=False)),
                ('approval_status', models.CharField(
                    choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                    default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_id', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='doctor_profile',
                    to='auth_app.logincredentials')),
                ('hospital_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='doctors',
                    to='hospital.hospitalregistration')),
                ('dept_id', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='doctors',
                    to='hospital.department')),
            ],
            options={'db_table': 'doctor_registrations'},
        ),
        migrations.CreateModel(
            name='DoctorSlot',
            fields=[
                ('slot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('consult_type', models.CharField(
                    choices=[('online', 'Online'), ('in_person', 'In Person')],
                    default='online', max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='slots',
                    to='doctor.doctorregistration')),
            ],
            options={'db_table': 'doctor_slots'},
        ),
    ]
