# Generated by Django 4.2

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jitsi_room_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(
                    choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'),
                             ('completed', 'Completed'), ('cancelled', 'Cancelled')],
                    default='scheduled', max_length=15)),
                ('ai_suggestions', models.JSONField(blank=True, default=dict)),
                ('doctor_notes', models.TextField(blank=True)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('to_emergency', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(
                    choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')],
                    default='pending', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='consultations',
                    to='doctor.doctorregistration')),
                ('patient_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='consultations',
                    to='patient.patientregistration')),
                ('slot_id', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='consultation',
                    to='doctor.doctorslot')),
            ],
            options={'db_table': 'consultations', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicines', models.JSONField(default=list)),
                ('diagnosis', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('pdf_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation_id', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='prescription',
                    to='doctor.consultation')),
                ('doctor_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='prescriptions',
                    to='doctor.doctorregistration')),
                ('patient_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='prescriptions',
                    to='patient.patientregistration')),
            ],
            options={'db_table': 'prescriptions', 'ordering': ['-created_at']},
        ),
    ]
