# Generated by Django 5.2.14 on 2026-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_consultation_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consult_mode',
            field=models.CharField(choices=[('online', 'Online Video Call'), ('offline', 'Physical Visit')], default='online', max_length=20),
        ),
    ]
