# Generated by Django 5.2.13 on 2026-05-06 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('doctor', '0002_consultation_prescription'),
        ('hospital', '0002_add_bed'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tests_ordered', models.JSONField(default=list)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='doctor.doctorregistration')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patient.patientregistration')),
            ],
            options={
                'db_table': 'lab_orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('results', models.JSONField(default=dict)),
                ('report_file_url', models.CharField(blank=True, max_length=500)),
                ('abnormal_flags', models.JSONField(default=list)),
                ('ai_analysis', models.TextField(blank=True)),
                ('saved_to_ehr', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lab.laborder')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patient.patientregistration')),
            ],
            options={
                'db_table': 'lab_reports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTechRegistration',
            fields=[
                ('lab_tech_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_technicians', to='hospital.hospitalregistration')),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tech_profile', to='auth_app.logincredentials')),
            ],
            options={
                'db_table': 'lab_tech_registrations',
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='lab_tech_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='lab.labtechregistration'),
        ),
    ]
