# Generated by Django 5.0.14 on 2026-05-30 12:16

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_bed_emergency_id'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestSlotRule',
            fields=[
                ('rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name_keyword', models.CharField(help_text='Keyword to match test name', max_length=100)),
                ('time_restriction', models.CharField(choices=[('any', 'Any Time'), ('morning', 'Morning Only'), ('specific', 'Specific Window')], default='any', max_length=20)),
                ('allowed_start', models.TimeField(blank=True, default=datetime.time(8, 0), null=True)),
                ('allowed_end', models.TimeField(blank=True, default=datetime.time(11, 0), null=True)),
                ('requires_fasting', models.BooleanField(default=False)),
                ('fasting_hours', models.IntegerField(default=0)),
                ('preparation_note', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'lab_test_slot_rules',
            },
        ),
        migrations.CreateModel(
            name='HospitalLabConfig',
            fields=[
                ('config_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('working_days', models.JSONField(default=list, help_text='List of days: [0=Mon,1=Tue...]')),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('end_time', models.TimeField(default=datetime.time(18, 0))),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('max_patients_per_slot', models.IntegerField(default=5)),
                ('lunch_break_start', models.TimeField(blank=True, default=datetime.time(13, 0), null=True)),
                ('lunch_break_end', models.TimeField(blank=True, default=datetime.time(14, 0), null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('advance_booking_days', models.IntegerField(default=30, help_text='How many days ahead to generate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_config', to='hospital.hospitalregistration')),
            ],
            options={
                'db_table': 'hospital_lab_configs',
            },
        ),
        migrations.CreateModel(
            name='LabSlot',
            fields=[
                ('slot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_patients', models.IntegerField(default=5)),
                ('booked_count', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_slots', to='hospital.hospitalregistration')),
            ],
            options={
                'db_table': 'lab_slots',
                'ordering': ['slot_date', 'start_time'],
                'unique_together': {('hospital_id', 'slot_date', 'start_time')},
            },
        ),
    ]
