# Generated by Django 5.2.13 on 2026-05-06 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_add_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemicTrend',
            fields=[
                ('trend_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('case_count', models.IntegerField(default=0)),
                ('spike_detected', models.BooleanField(default=False)),
                ('heatmap_data', models.JSONField(blank=True, default=list)),
                ('alert_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('recorded_date', models.DateField()),
            ],
            options={
                'db_table': 'epidemic_trends',
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='FLGlobalModel',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('weights_file_url', models.CharField(blank=True, max_length=500)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hospitals_count', models.IntegerField(default=0)),
                ('aggregation_algo', models.CharField(default='FedAvg', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('privacy_epsilon', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fl_global_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FLRound',
            fields=[
                ('round_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('aggregating', 'Aggregating'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('hospitals_invited', models.IntegerField(default=0)),
                ('hospitals_completed', models.IntegerField(default=0)),
                ('global_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='federated.flglobalmodel')),
            ],
            options={
                'db_table': 'fl_rounds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FLHospitalWeight',
            fields=[
                ('weight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weights_file_url', models.CharField(blank=True, max_length=500)),
                ('local_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('local_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('noise_added', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fl_weights', to='hospital.hospitalregistration')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_weights', to='federated.flround')),
            ],
            options={
                'db_table': 'fl_hospital_weights',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
