# Generated by Django 5.2.14 on 2026-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federated', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flround',
            name='auto_aggregated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flround',
            name='min_hospitals_threshold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flround',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flround',
            name='round_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
