# Generated by Django 5.2.14 on 2026-05-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federated', '0002_flround_auto_aggregated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flround',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('aggregating', 'Aggregating'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
