# Generated by Django 5.2.14 on 2026-05-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('federated', '0003_alter_flround_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemictrend',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epidemictrend',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='epidemictrend',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epidemictrend',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_epidemics', to='auth_app.logincredentials'),
        ),
    ]
