# Generated by Django 5.2.13 on 2026-05-06 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCredentials',
            fields=[
                ('login_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab Technician'), ('driver', 'Ambulance Driver'), ('vendor', 'Equipment Vendor')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Login Credential',
                'db_table': 'login_credentials',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='auth_app.logincredentials')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jwt_token_hash', models.CharField(max_length=300)),
                ('device_info', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='auth_app.logincredentials')),
            ],
            options={
                'db_table': 'login_sessions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('notif_type', models.CharField(choices=[('approval', 'Approval'), ('alert', 'Alert'), ('reminder', 'Reminder'), ('order', 'Order'), ('emergency', 'Emergency'), ('report', 'Report Ready'), ('payment', 'Payment')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='auth_app.logincredentials')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab Technician'), ('driver', 'Ambulance Driver'), ('vendor', 'Equipment Vendor')], max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role_permissions',
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('profile_photo', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_profile', to='auth_app.logincredentials')),
            ],
            options={
                'db_table': 'super_admin',
            },
        ),
    ]
