# Generated by Django 4.2 — rewritten to break circular dependency with patient/doctor

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRegistration',
            fields=[
                ('hospital_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=200)),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('doc_url', models.CharField(blank=True, max_length=500)),
                ('telemedicine_enabled', models.BooleanField(default=False)),
                ('approval_status', models.CharField(
                    choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                    default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_id', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='hospital_profile',
                    to='auth_app.logincredentials')),
            ],
            options={'db_table': 'hospital_registrations'},
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='departments',
                    to='hospital.hospitalregistration')),
            ],
            options={'db_table': 'departments'},
        ),
        migrations.CreateModel(
            name='HospitalInventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(
                    choices=[('medicine', 'Medicine'), ('equipment', 'Equipment'), ('supply', 'Supply')],
                    max_length=15)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reorder_level', models.IntegerField(default=10)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('maintenance_due', models.DateField(blank=True, null=True)),
                ('hospital_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='inventory',
                    to='hospital.hospitalregistration')),
            ],
            options={'db_table': 'hospital_inventory'},
        ),
    ]
