# Generated by Django 4.2 — Bed added after patient app is available

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_type', models.CharField(
                    choices=[('general', 'General'), ('icu', 'ICU'), ('ventilator', 'Ventilator')],
                    max_length=15)),
                ('ward_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(
                    choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')],
                    default='available', max_length=10)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='beds',
                    to='hospital.hospitalregistration')),
                ('reserved_for', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='reserved_beds',
                    to='patient.patientregistration')),
            ],
            options={'db_table': 'beds'},
        ),
    ]
