# Generated by Django 5.2.14 on 2026-05-13 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('hospital', '0003_add_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPatient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('symptoms', models.JSONField(default=list)),
                ('diagnosis', models.CharField(max_length=200)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.logincredentials')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_patients', to='hospital.hospitalregistration')),
            ],
            options={
                'db_table': 'hospital_patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
