# Generated by Django 5.2.14 on 2026-05-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospitalpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalinventory',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='hospitalinventory',
            name='category',
            field=models.CharField(choices=[('medical_equipment', 'Medical Equipment'), ('diagnostic', 'Diagnostic Equipment'), ('surgical', 'Surgical Equipment'), ('monitoring', 'Monitoring Equipment'), ('emergency', 'Emergency Equipment'), ('laboratory', 'Laboratory Equipment'), ('imaging', 'Imaging Equipment'), ('therapy', 'Therapy Equipment'), ('furniture', 'Furniture'), ('other', 'Other')], default='medical_equipment', max_length=30),
        ),
    ]
