# Generated by Django 5.2.14 on 2026-05-27 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0006_ambulancedispatch_reroute_count_and_more'),
        ('hospital', '0005_hospitalinventory_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='emergency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reserved_beds', to='emergency.emergencyrequest'),
        ),
    ]
