# Generated by Django 5.2.13 on 2026-05-06 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSession',
            fields=[
                ('triage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.JSONField(default=list)),
                ('predicted_disease', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommendations', models.TextField(blank=True)),
                ('escalated_to_emergency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_sessions', to='patient.patientregistration')),
            ],
            options={
                'db_table': 'triage_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
