# Generated by Django 5.2.13 on 2026-05-06 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('auth_app', '0001_initial'),
        ('hospital', '0002_add_bed'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceDriverRegistration',
            fields=[
                ('driver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('license_no', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='hospital.hospitalregistration')),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='auth_app.logincredentials')),
            ],
            options={
                'db_table': 'ambulance_driver_registrations',
            },
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('ambulance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=20, unique=True)),
                ('ambulance_type', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('neonatal', 'Neonatal')], default='basic', max_length=10)),
                ('equipment_list', models.JSONField(default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='hospital.hospitalregistration')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='emergency.ambulancedriverregistration')),
            ],
            options={
                'db_table': 'ambulances',
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('emergency_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('patient_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('severity', models.CharField(choices=[('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_bed_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='hospital.bed')),
                ('assigned_hospital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='hospital.hospitalregistration')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='patient.patientregistration')),
                ('triage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='ai_engine.triagesession')),
            ],
            options={
                'db_table': 'emergency_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceDispatch',
            fields=[
                ('dispatch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_status', models.CharField(choices=[('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed')], default='dispatched', max_length=15)),
                ('eta_minutes', models.IntegerField(blank=True, null=True)),
                ('route_data', models.JSONField(default=list)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ambulance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='emergency.ambulance')),
                ('emergency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='emergency.emergencyrequest')),
            ],
            options={
                'db_table': 'ambulance_dispatch',
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
