# Generated by Django 5.2.14 on 2026-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancedispatch',
            name='dispatch_status',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('pending_acknowledgment', 'Pending Acknowledgment'), ('completed', 'Completed')], default='dispatched', max_length=25),
        ),
    ]
