# Generated by Django 5.2.14 on 2026-05-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_alter_ambulancedispatch_dispatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedispatch',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
