# Generated by Django 5.2.14 on 2026-05-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_ambulancedispatch_accepted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('no_drivers', 'No Drivers Available'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
