# Generated by Django 5.2.14 on 2026-05-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_alter_emergencyrequest_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedispatch',
            name='reroute_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ambulancedispatch',
            name='rerouted',
            field=models.BooleanField(default=False),
        ),
    ]
