# Generated by Django 5.2.14 on 2026-05-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0006_ambulancedispatch_reroute_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedispatch',
            name='bed_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ambulancedispatch',
            name='bed_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
