# Generated by Django 4.2

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('gender', models.CharField(
                    blank=True,
                    choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')],
                    max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('qr_code_url', models.CharField(blank=True, max_length=500)),
                ('lifestyle_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_id', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='patient_profile',
                    to='auth_app.logincredentials')),
            ],
            options={'db_table': 'patient_registrations'},
        ),
        migrations.CreateModel(
            name='EHRRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(
                    choices=[('diagnosis', 'Diagnosis'), ('lab', 'Lab'), ('prescription', 'Prescription'),
                             ('history', 'History'), ('allergy', 'Allergy')],
                    max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='added_records',
                    to='auth_app.logincredentials')),
                ('patient_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ehr_records',
                    to='patient.patientregistration')),
            ],
            options={'db_table': 'ehr_records', 'ordering': ['-recorded_at']},
        ),
        migrations.CreateModel(
            name='EHRConsentLog',
            fields=[
                ('consent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(
                    choices=[('qr_scan', 'QR Scan'), ('manual', 'Manual'), ('emergency', 'Emergency')],
                    max_length=15)),
                ('data_shared', models.JSONField(blank=True, default=list)),
                ('consent_given', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ehr_accesses',
                    to='auth_app.logincredentials')),
                ('patient_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='consent_logs',
                    to='patient.patientregistration')),
            ],
            options={'db_table': 'ehr_consent_log', 'ordering': ['-accessed_at']},
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.CharField(max_length=200)),
                ('reaction', models.TextField(blank=True)),
                ('severity', models.CharField(
                    blank=True,
                    choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')],
                    max_length=10)),
                ('noted_at', models.DateTimeField(auto_now_add=True)),
                ('noted_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='noted_allergies',
                    to='doctor.doctorregistration')),
                ('patient_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='allergies',
                    to='patient.patientregistration')),
            ],
            options={'db_table': 'allergies'},
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('risk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diabetes_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heart_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hypertension_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_level', models.CharField(
                    blank=True,
                    choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')],
                    max_length=10)),
                ('recommendations', models.TextField(blank=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='risk_assessments',
                    to='patient.patientregistration')),
            ],
            options={'db_table': 'risk_assessments', 'ordering': ['-assessed_at']},
        ),
    ]
