# Generated by Django 4.2 on 2026-05-18 05:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_consultation_prescription'),
        ('auth_app', '0001_initial'),
        ('vendor', '0002_equipmentorder_delivered_at_and_more'),
        ('hospital', '0004_hospitalpatient'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tests', models.JSONField(default=list)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('report_url', models.URLField(blank=True)),
                ('report_results', models.JSONField(default=dict)),
                ('abnormal_flags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctorregistration')),
                ('hospital_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospitalregistration')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_orders', to='patient.patientregistration')),
            ],
            options={
                'db_table': 'lab_test_orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='EHRImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('xray', 'X-Ray'), ('mri', 'MRI Scan'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('other', 'Other')], max_length=20)),
                ('image_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehr_images', to='patient.patientregistration')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.logincredentials')),
            ],
            options={
                'db_table': 'ehr_images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_type', models.CharField(choices=[('doctor', 'Doctor Complaint'), ('vendor', 'Vendor Complaint')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='doctor.doctorregistration')),
                ('hospital_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospitalregistration')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='patient.patientregistration')),
                ('vendor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='vendor.vendorregistration')),
            ],
            options={
                'db_table': 'patient_complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
