# Generated by Django 5.2.14 on 2026-05-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_labtestorder_ehrimage_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehrconsentlog',
            name='short_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
