# Generated by Django 5.2.14 on 2026-05-25 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_hospitalinventory_image_url_and_more'),
        ('patient', '0003_ehrconsentlog_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='filed_by_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_complaints', to='hospital.hospitalregistration'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='hospital_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='hospital_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='patient_followup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='patient.patientregistration'),
        ),
    ]
