# Generated by Django 4.2 on 2026-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_complaint_admin_replied_complaint_filed_by_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
