# Generated by Django 5.0.14 on 2026-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientregistration_reminder_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestorder',
            name='prescription_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='prescription_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('doctor_referred', 'Doctor Referred')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='prescription_verified',
            field=models.BooleanField(default=False),
        ),
    ]
