# Generated by Django 5.0.14 on 2026-05-30 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labtestslotrule_hospitallabconfig_labslot'),
        ('patient', '0006_labtestorder_prescription_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestorder',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestorder',
            name='slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='lab.labslot'),
        ),
    ]
