# Generated by Django 4.2 on 2026-06-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_labtestorder_reminder_sent_labtestorder_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehrimage',
            name='image_type',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('mri', 'MRI Scan'), ('skin', 'Skin Photo'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('other', 'Other')], max_length=20),
        ),
    ]
