from django.urls import path
from .views import (
    DoctorDashboardView,
    ToggleOnlineStatusView,
    GetPatientEHRView,
    CreateSlotView,
    ListSlotsView,
    DoctorConsultationsView,
    UpdateConsultationView,
    CreatePrescriptionView,
    CreateLabOrderView,
    DoctorLabOrdersView,
    VerifyPaymentView,
    DoctorPatientsView,
    ValidateConsentView,
    DoctorPrescriptionsView,
    DownloadPrescriptionView,
    PublicPrescriptionDownloadView,
    SearchPatientView,
    CreateOfflineConsultationView,
)

urlpatterns = [
    path('dashboard/', DoctorDashboardView.as_view()),
    path('toggle-online/', ToggleOnlineStatusView.as_view()),
    path('patients/', DoctorPatientsView.as_view()),
    path('search-patient/', SearchPatientView.as_view()),
    path('patient-ehr/<uuid:patient_id>/', GetPatientEHRView.as_view()),
    path('validate-consent/', ValidateConsentView.as_view()),
    path('offline-consultation/create/', CreateOfflineConsultationView.as_view()),
    path('slots/', ListSlotsView.as_view()),
    path('slots/create/', CreateSlotView.as_view()),
    path('consultations/', DoctorConsultationsView.as_view()),
    path('consultations/<uuid:consultation_id>/', UpdateConsultationView.as_view()),
    path('prescriptions/', DoctorPrescriptionsView.as_view()),
    path('prescriptions/create/', CreatePrescriptionView.as_view()),
    path('prescriptions/<uuid:prescription_id>/download/', DownloadPrescriptionView.as_view()),
    path('prescriptions/<uuid:prescription_id>/pdf/', PublicPrescriptionDownloadView.as_view()),
    path('lab-orders/', DoctorLabOrdersView.as_view()),
    path('lab-orders/create/', CreateLabOrderView.as_view()),
    path('verify-payment/', VerifyPaymentView.as_view()),
]
