# Generated by Django 5.2.13 on 2026-05-06 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('doctor', '0002_consultation_prescription'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacistRegistration',
            fields=[
                ('pharmacist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(max_length=200)),
                ('license_no', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to='auth_app.logincredentials')),
            ],
            options={
                'db_table': 'pharmacist_registrations',
            },
        ),
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('med_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicines', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('delivery_address', models.TextField(blank=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='pending', max_length=15)),
                ('tracking_info', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_orders', to='patient.patientregistration')),
                ('prescription_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_orders', to='doctor.prescription')),
                ('pharmacist_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pharmacy.pharmacistregistration')),
            ],
            options={
                'db_table': 'medicine_orders',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
