# Generated by Django 4.2 on 2026-05-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='estimated_delivery_days',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='prescription_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='prescription_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='requires_prescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='status_history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('prescription_required', 'Prescription Required'), ('prescription_uploaded', 'Prescription Uploaded'), ('verified', 'Verified'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
