# Generated by Django 5.2.14 on 2026-05-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacyinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='payment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='prescription_local_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='prescription_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('prescription_required', 'Prescription Required'), ('awaiting_prescription', 'Awaiting Prescription'), ('prescription_uploaded', 'Prescription Uploaded'), ('prescription_approved', 'Prescription Approved'), ('verified', 'Verified'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
