# Generated by Django 5.2.14 on 2026-05-19 04:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_medicineorder_payment_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinventory',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='medicine_images/'),
        ),
    ]
