# Generated by Django 5.2.14 on 2026-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_pharmacyinventory_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinventory',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
