from django.urls import path
from .views import (
    FLDashboardView,
    InitializeGlobalModelView,
    StartFLRoundView,
    SubmitLocalWeightsView,
    HospitalSubmissionHistoryView,
    AggregateWeightsView,
    GetRoundDetailsView,
    ListRoundsView,
    EpidemicTrendsView,
    CreateEpidemicTrendView,
    ResolveEpidemicView,
    AutoDetectEpidemicView,
    HospitalFLStatusView,
    ResetFLDataView,
    SimulateAllHospitalsView,
    BroadcastAlertView,
    SendReminderView,
    ForceAggregateView,
    ExtendDeadlineView,
    CancelRoundView,
    LowerThresholdView,
)

urlpatterns = [
    path('dashboard/', FLDashboardView.as_view(), name='fl-dashboard'),
    path('initialize/', InitializeGlobalModelView.as_view(), name='fl-initialize'),
    path('start-round/', StartFLRoundView.as_view(), name='fl-start-round'),
    path('submit-weights/', SubmitLocalWeightsView.as_view(), name='fl-submit-weights'),
    path('my-submissions/', HospitalSubmissionHistoryView.as_view(), name='fl-my-submissions'),
    path('aggregate/', AggregateWeightsView.as_view(), name='fl-aggregate'),
    path('rounds/', ListRoundsView.as_view(), name='fl-rounds-list'),
    path('rounds/<uuid:round_id>/', GetRoundDetailsView.as_view(), name='fl-round-details'),
    path('epidemic/', EpidemicTrendsView.as_view(), name='fl-epidemic-list'),
    path('epidemic/create/', CreateEpidemicTrendView.as_view(), name='fl-epidemic-create'),
    path('epidemic/<uuid:trend_id>/resolve/', ResolveEpidemicView.as_view(), name='fl-epidemic-resolve'),
    path('epidemic/broadcast/', BroadcastAlertView.as_view(), name='fl-epidemic-broadcast'),
    path('epidemic/auto-detect/', AutoDetectEpidemicView.as_view(), name='fl-epidemic-auto-detect'),
    path('hospital-status/', HospitalFLStatusView.as_view(), name='fl-hospital-status'),
    path('reset/', ResetFLDataView.as_view(), name='fl-reset'),
    path('simulate-all/', SimulateAllHospitalsView.as_view(), name='fl-simulate-all'),
    path('send-reminder/', SendReminderView.as_view(), name='fl-send-reminder'),
    path('force-aggregate/', ForceAggregateView.as_view(), name='fl-force-aggregate'),
    path('extend-deadline/', ExtendDeadlineView.as_view(), name='fl-extend-deadline'),
    path('cancel-round/', CancelRoundView.as_view(), name='fl-cancel-round'),
    path('lower-threshold/', LowerThresholdView.as_view(), name='fl-lower-threshold'),
]
